# Generated by Django 3.1 on 2021-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id_denuncia', models.AutoField(db_column='id_Denuncia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'denuncias',
                'managed': False,
            },
        ),
    ]
