# Generated by Django 3.1 on 2021-03-15 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotasAdopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_nombre', models.CharField(blank=True, max_length=11)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('vacunas', models.IntegerField()),
                ('castracion', models.IntegerField()),
                ('atencion_especial', models.IntegerField()),
                ('des_at_especial', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField()),
                ('id_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mascotas_adopcion',
            },
        ),
    ]
