# Generated by Django 3.1 on 2021-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MascotasAdopcion',
            fields=[
                ('a_mascotas', models.AutoField(db_column='A_Mascotas', primary_key=True, serialize=False)),
                ('a_nombre', models.CharField(blank=True, max_length=11)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('vacunas', models.IntegerField()),
                ('castracion', models.IntegerField()),
                ('atencion_especial', models.IntegerField()),
                ('des_at_especial', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'mascotas_adopcion',
                'managed': False,
            },
        ),
    ]
