# Generated by Django 3.1 on 2021-03-20 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotasadopcion',
            name='atencion_especial',
        ),
        migrations.RemoveField(
            model_name='mascotasadopcion',
            name='castracion',
        ),
        migrations.RemoveField(
            model_name='mascotasadopcion',
            name='des_at_especial',
        ),
        migrations.RemoveField(
            model_name='mascotasadopcion',
            name='vacunas',
        ),
    ]
