# Generated by Django 3.1 on 2021-03-08 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id_denuncia', models.AutoField(db_column='id_Denuncia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'denuncias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotasAdopcion',
            fields=[
                ('a_mascotas', models.AutoField(db_column='A_Mascotas', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('vacunas', models.IntegerField()),
                ('castracion', models.IntegerField()),
                ('atencion_especial', models.IntegerField()),
                ('des_at_especial', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'mascotas_adopcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MascotaTransito',
            fields=[
                ('t_mascotas', models.AutoField(db_column='T_Mascotas', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('tiempo', models.CharField(blank=True, db_column='Tiempo', max_length=15, null=True)),
                ('vacunas', models.IntegerField(blank=True, null=True)),
                ('castracion', models.IntegerField(blank=True, null=True)),
                ('atencion_especial', models.IntegerField(blank=True, null=True)),
                ('des_at_especial', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascota_transito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinarias',
            fields=[
                ('id_vet', models.AutoField(db_column='id_Vet', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'veterinarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id_duenio', models.OneToOneField(db_column='id_duenio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base_datos.usuario')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'adopcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transito',
            fields=[
                ('id_duenio', models.OneToOneField(db_column='id_duenio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='solicitante', serialize=False, to='base_datos.usuario')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'transito',
                'managed': False,
            },
        ),
    ]
