# Generated by Django 3.1 on 2021-03-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
