# Generated by Django 3.1 on 2021-03-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('receptor', models.ForeignKey(db_column='receptor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='solicitante', serialize=False, to='usuario.usuario')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='creado')),
                ('mensaje', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Mensajes',
                'managed': False,
            },
        ),
    ]
